# compose file for running mysql database, scadalts and mosquitto broker
version: '3'
services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:5.7
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            -   ./docker/volumes/databases:/home/
    scadalts:
        container_name: scadalts
        image: scadalts/scadalts:v2.7.2
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        links:
            - database:database
        command:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:2
        volumes:
          - ./mosquitto-config/:/mosquitto/config/
        #   - ./log/:/mosquitto/log/
        #   - data:/mosquitto/data/
        ports:
          - 1883:1883
          - 9001:9001
        expose: ["1883"]

# volumes:
#   data: .